twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']symfony run yarn devsymfony run yarn devsymfony run -d yarn dev --watchsymfony run -d yarn dev --watch

when@test:
    twig:
        strict_variables: true
